apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hbkzqpj1m-python
  janus-idp.io/tekton: hbkzqpj1m-python
  backstage.io/kubernetes-id: hbkzqpj1m-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hbkzqpj1m-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
